[package]
name = "context_menu_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.74", features = ["full"] }

proc-macro2 = "1.0.86"
quote = "1.0.36"
[lib]
proc-macro = true
