[package]
name = "leptos_context_menu"
version = "0.1.0"
edition = "2021"
description = "A library for generating context menus in Leptos."
license = "MIT"
repository = "https://github.com/Ovenoboyo/leptos_context_menu"
readme = "README.md"
keywords = ["leptos", "ui", "menu", "context-menu", "wasm"]
categories = ["web-programming", "wasm"]

[dependencies]
leptos = { version = "0.8.11", features = ["csr"] }
leptos-use = "0.16.3"
uuid = { version = "1.18.1", features = ["v4", "js"] }
wasm-bindgen = "0.2.104"
web-sys = "0.3.81"

[dev-dependencies]
console_error_panic_hook = "0.1.7"
